import '../App.css'

export default function Table({people}) {

    return (
        <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Height</th>
            <th>Hair Color</th>
            <th>Gender</th>
          </tr>
        </thead>
        <tbody>
          <tr>
                <td>{people[0].name}</td>
                <td>{people[0].height}</td>
                <td>{people[0].hair_color}</td>
                <td>{people[0].gender}</td>
            </tr>
          <tr>
                <td>{people[1].name}</td>
                <td>{people[1].height}</td>
                <td>{people[1].hair_color}</td>
                <td>{people[1].gender}</td>
                </tr>
            <tr>
                <td>{people[2].name}</td>
                <td>{people[2].height}</td>
                <td>{people[2].hair_color}</td>
                <td>{people[2].gender}</td>
                </tr>
            <tr>
                <td>{people[3].name}</td>
                <td>{people[3].height}</td>
                <td>{people[3].hair_color}</td>
                <td>{people[3].gender}</td>
                </tr>
            <tr>
                <td>{people[4].name}</td>
                <td>{people[4].height}</td>
                <td>{people[4].hair_color}</td>
                <td>{people[4].gender}</td>
                </tr>
            <tr>
                <td>{people[5].name}</td>
                <td>{people[5].height}</td>
                <td>{people[5].hair_color}</td>
                <td>{people[5].gender}</td>
                </tr>
            <tr>
                <td>{people[6].name}</td>
                <td>{people[6].height}</td>
                <td>{people[6].hair_color}</td>
                <td>{people[6].gender}</td>
                </tr>
            <tr>
                <td>{people[7].name}</td>
                <td>{people[7].height}</td>
                <td>{people[7].hair_color}</td>
                <td>{people[7].gender}</td>
                </tr>
            <tr>
                <td>{people[8].name}</td>
                <td>{people[8].height}</td>
                <td>{people[8].hair_color}</td>
                <td>{people[8].gender}</td>
                </tr>
            <tr>
                <td>{people[9].name}</td>
                <td>{people[9].height}</td>
                <td>{people[9].hair_color}</td>
                <td>{people[9].gender}</td>
                </tr>
        </tbody>
      </table>
    );
  };
